<a href="https://colab.research.google.com/github/Pradipkumar62075/python/blob/main/Tensorflow_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.
<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.11/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [8]:
pradip = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)
print(pradip)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>


In [10]:
rank1_tensor = tf.Variable([["Test","successful","then"],["pradip","hello","what"]], tf.string)
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)
print(rank1_tensor)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=string, numpy=
array([[b'Test', b'successful', b'then'],
       [b'pradip', b'hello', b'what']], dtype=object)>


In [15]:
tensor1 = tf.zeros([1,2,3])
print(tensor1) # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1])
print(tensor2) # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
print(tensor3)                                       # this will reshape the tensor to [3,3]


tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)
